# ✅ NETLIFY KONFIGURATION für Märitkorb Wareneingangskontrolle
# Optimiert für Next.js 15 mit OpenNext Adapter

[build]
  # ✅ NETLIFY BUILD: Standard Next.js Build-Command
  command = "npm run build"
  
  # ✅ NETLIFY PUBLISH: Next.js App Router Output-Directory
  # Netlify's OpenNext Adapter erkennt automatisch .next Ordner
  publish = ".next"
  
  # ✅ NETLIFY NODE VERSION: Kompatibel mit Next.js 15
  [build.environment]
    NODE_VERSION = "18"
    # Optimiert für Netlify's Build-Performance
    NPM_FLAGS = "--production=false"

# ✅ NETLIFY REDIRECTS: SPA-Routing für Next.js App Router
# Alle unbekannten Routen werden an Next.js weitergeleitet
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Nur für statische Dateien, die nicht existieren
  conditions = {Role = []}

# ✅ NETLIFY HEADERS: Sicherheit und Performance-Optimierung
[[headers]]
  for = "/*"
  [headers.values]
    # Sicherheits-Headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance-Headers für statische Assets
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    # HTML-Dateien nicht cachen für dynamische Inhalte
    Cache-Control = "public, max-age=0, must-revalidate"

# ✅ NETLIFY FUNCTIONS: Automatische Erkennung durch OpenNext
# Keine manuelle Konfiguration nötig - OpenNext macht das automatisch

# ✅ NETLIFY EDGE FUNCTIONS: Für Next.js Middleware (falls verwendet)
# Automatisch durch OpenNext Adapter konfiguriert

# ✅ NETLIFY FORMS: Deaktiviert (nicht benötigt für diese App)
# Falls später benötigt, kann aktiviert werden

# ✅ NETLIFY IMAGE CDN: Automatisch durch next.config.mjs aktiviert
# Keine zusätzliche Konfiguration nötig
